version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travelshare-backend
    ports:
      - "8080:8080"
    # environment:
    #   - SPRING_PROFILES_ACTIVE=prod
    #   - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
    #   - SPRING_DATASOURCE_USERNAME=postgres
    #   - SPRING_DATASOURCE_PASSWORD=secret
    # Muut ympäristömuuttujat tai riippuvuudet, jos tarvetta
    # depends_on:
    #   - database
